config/routes.rb
Investours::Application.routes.draw do
  resource :dashboard, only: [:show]
  resources :entrepreneurs do
      resources :projects, only: [:show, :edit, :update]
  end
  resources :loans
  resources :payments
  resources :sign_ups
  resources :tours
  resources :updates, only: [:create, :update, :destroy]
  devise_for :users
  get 'users/search', to: "users#search"
  get 'home', to: "visitors#welcome"
  
  authenticated :user do
    root :to => "dashboards#show"
  end
  root to: "visitors#welcome"
end

app/models/entrepreneur.rb
class Entrepreneur < ActiveRecord::Base
  extend FriendlyId
  attr_accessible :first_name, :last_name, :location, :tour_ids, :filepicker_url, :slug
  
  validates :first_name, :last_name, presence: true
  
  has_many :tour_meetings, inverse_of: :entrepreneur, dependent: :destroy
  has_many :tours, through: :tour_meetings, inverse_of: :entrepreneurs
  
  has_many :loans, dependent: :destroy
  has_many :creditors, through: :loans, source: :investor
  
  has_many :projects, dependent: :destroy
  
  def full_name
    first_name + " " + last_name
  end
  
  friendly_id :full_name, use: :slugged  
  
end

app/controllers/entrepreneurs_controller.rb
class EntrepreneursController < ApplicationController
  
  def index
    @entrepreneurs = Entrepreneur.all
  end
  
  def show
    @entrepreneur = Entrepreneur.find(params[:id])
    @projects = @entrepreneur.projects
  end
  
  def new
    @entrepreneur = Entrepreneur.new
    @tours = Tour.where("date > ?", Date.current)
    
    authorize! :create, @entrepreneur
  end
  
  def create
    @entrepreneur = Entrepreneur.new(params[:entrepreneur])
    
    if @entrepreneur.save
      redirect_to entrepreneur_url(@entrepreneur)
      flash[:notice] = "#{@entrepreneur.first_name} #{@entrepreneur.last_name} successfully added."
    else
      flash.now[:error] = @entrepreneur.errors.full_messages
      render action: "new"
    end
  end
  
  def edit
    @entrepreneur = Entrepreneur.find(params[:id])
    @tours = Tour.where("date > ?", Date.current)
    authorize! :update, @entrepreneur
  end
  
  def update
    @entrepreneur = Entrepreneur.update_attributes(params[:entrepreneur])
    
    if @entrepreneur.save
      redirect_to entrepreneur_url(@entrepreneur)
      flash[:notice] = "#{@entrepreneur.first_name} #{@entrepreneur.last_name} successfully updated."
    else
      flash.now[:error] = @entrepreneur.errors.full_messages
      render action: "edit"
    end
  end
  
  def destroy
    @entrepreneur = Entrepreneur.find(params[:id])
    @entrepreneur.destroy
    redirect_to entrepreneurs_url
  end
  
end

app/helpers/entrepreneurs_helper.rb
module EntrepreneursHelper
end

app/views/entrepreneurs/_form.html.erb
<form for="entrepreneur" action="<%= entrepreneurs_url %>" method="POST">
	<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
	<label for="entrepreneur_first_name">First Name</label>
	<input id="entrepreneur_first_name" name="entrepreneur[first_name]" type="text" value="<%= @entrepreneur.first_name %>">
	<br>
	<label for="entrepreneur_last_name">Last Name</label>
	<input id="entrepreneur_last_name" name="entrepreneur[last_name]" type="text" value="<%= @entrepreneur.last_name %>">
	<br>
	<label for="entrepreneur_filepicker_url">Portrait</label>
	<input id="entrepreneur_filepicker_url" name="entrepreneur[filepicker_url]" type="filepicker">
	<br>	
	<label for="entrepreneur_location">Location</label>
	<input id="entrepreneur_location" name="entrepreneur[location]" type="text" value="<%= @entrepreneur.location %>">
	<br>
	<label for="entrepreneur_tour">Tour</label>
	<select id="entrepreneur_tour" name="entrepreneur[tour_ids]">
		<% @tours.each do |tour| %>
		<option value="<%= tour.id %>"
			<% if tour.entrepreneurs.include? @entrepreneur %>
			selected="selected"
			<% end %>
		>
			
			<%= tour.location %> on <%= tour.date %>
		</option>
		<% end %>
	</select>
	<input type="Submit" value="Submit" >
</form>

app/views/entrepreneurs/_projects_list.html.erb
<h4><%= @entrepreneur.first_name %>'s projects</h4>
<div id="entrepreneur_projects_list">
<ul>
	<% @entrepreneur.projects.each do |project| %>
	<li>
		<%= render partial: "projects/mini_show", locals: { project: project } %>
		<% if current_user && current_user.role == 'admin' %>
			<p><%= link_to "Update this project", edit_entrepreneur_project_url(@entrepreneur, project), method: :get  %></p>
		<% end %>
	</li>
	<% end %>
</ul>
</div>

app/views/entrepreneurs/edit.html.erb
<h1>Edit entrepreneur</h1>

<%= render "form", locals: { entrepreneur: @entrepreneur, tours: @tours } %>

<%= link_to 'Back', :back %>

app/views/entrepreneurs/index.html.erb
<ul>
	<% @entrepreneurs.each do |entrepreneur| %>
		<li>
			<%= link_to "#{entrepreneur.full_name}",
				entrepreneur_url(entrepreneur), method: :get %>
			<br>
			<%= entrepreneur.location %>
		</li>
		<% end %>
</ul>

<% if current_user && current_user.role == "admin" %>
	<%= link_to "Add an entrepreneur to the database", new_entrepreneur_url, method: :get %>
<% end %>

app/views/entrepreneurs/new.html.erb
<h1>Add an entrepreneur</h1>

<form for="entrepreneur" action="<%= entrepreneurs_url %>" method="POST">
	<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
	<label for="entrepreneur_first_name">First Name</label>
	<input id="entrepreneur_first_name" name="entrepreneur[first_name]" type="text">
	<br>
	<label for="entrepreneur_last_name">Last Name</label>
	<input id="entrepreneur_last_name" name="entrepreneur[last_name]" type="text">
	<br>
	<label for="entrepreneur_location">Location</label>
	<input id="entrepreneur_location" name="entrepreneur[location]" type="text">
	<br>
	<input type="Submit" value="Submit" >
</form>

<%= link_to 'Back', :back %>

app/views/entrepreneurs/show.html.erb
<div><%= filepicker_image_tag @entrepreneur.filepicker_url, w: 160, h: 160, fit: 'clip' %></div>
<h1><%= @entrepreneur.full_name %></h1>
<h4><%= @entrepreneur.location %></h4>

<% unless @entrepreneur.projects.empty? %>
	<%= render "projects_list", locals: { entrepreneur: @entrepreneur } %>
<% end %>

<% if user_is_admin? %>
<%= link_to "Edit #{@entrepreneur.full_name}", edit_entrepreneur_url(@entrepreneur), method: :get  %>
<%= button_to "Delete #{@entrepreneur.full_name}", entrepreneur_url(@entrepreneur), method: :delete, confirm: "Delete #{@entrepreneur.full_name}?" %>
<% end %>