config/routes.rb
Investours::Application.routes.draw do
  resource :dashboard, only: [:show]
  resources :entrepreneurs do
      resources :projects, only: [:show, :edit, :update]
  end
  resources :loans
  resources :payments
  resources :sign_ups
  resources :tours
  resources :updates, only: [:create, :update, :destroy]
  devise_for :users
  get 'users/search', to: "users#search"
  get 'home', to: "visitors#welcome"
  
  authenticated :user do
    root :to => "dashboards#show"
  end
  root to: "visitors#welcome"
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  attr_accessible :location, :date
  
  has_many :tour_sign_ups, inverse_of: :tour, dependent: :destroy
  has_many :travelers, through: :tour_sign_ups, source: :user, inverse_of: :tours
  
  has_many :tour_meetings, inverse_of: :tour, dependent: :destroy
  has_many :entrepreneurs, through: :tour_meetings, inverse_of: :tours
  
  def as_json(options = {})
    super(options.merge({ include: :entrepreneurs }))
  end
  
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  
  def show
    @tour = Tour.find(params[:id])
  end
  
  def index
    @tours = Tour.all
  end
  
  def new
    @tour = Tour.new
    authorize! :create, @tour
  end
  
  def create
    @tour = Tour.new(params[:tour])
        
    if @tour.save
      redirect_to tour_url(@tour)
      flash[:notice] = "New tour successfully added."
    else
      flash.now[:error] = @tour.errors.full_messages
      render action: "new"
    end
  end
  
  def edit
    @tour = Tour.find(params[:id])
  end
  
  def update
    @tour = Tour.update_attributes(params[:tour])
    
    if @tour.save
      redirect_to tour_url(@tour)
      flash[:notice] = "New tour successfully updated."
    else
      flash.now[:error] = @tour.errors.full_messages
      render action: "edit"
    end
  end
  
  def destroy
    @tour = Tour.find(params[:id])
    @tour.destroy
    redirect_to tour_url
  end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/index.html.erb
<h1>All Tours</h1>

<ul>
	<% @tours.each do |tour| %>
		<li>
			<%= link_to "#{tour.location}",
				tour_url(tour), method: :get %> on <%= tour.date %> 
		</li>
		<% end %>
</ul>

<div>
	<%= link_to_function "Back", "history.back()" %>
</div>

app/views/tours/new.html.erb
<h1>Add a tour</h1>

<form for="tour" action="<%= tours_url %>" method="POST">
	<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
	<label for="tour_location">Location</label>
	<input id="tour_location" name="tour[location]" type="text">
	<br>
	<label for="date">Date</label>
	<input id="date" name="tour[date]" type="text">
	<br>
	<input type="Submit" value="Submit" >
</form>

<%= link_to 'Back', :back %>

<script type="text/javascript">

$(function() {
    $( "#date" ).datepicker();
  });
	
</script>

app/views/tours/show.html.erb
<h1><%= @tour.location %></h1>

<p>On <%= @tour.date %></p>
<% if @tour.entrepreneurs.empty?%>
<p>Check back later to see which entrepreneurs you'll meet on this tour.</p>
<% else %>
<p>On this tour you will meet</p>
<ul>
	<% @tour.entrepreneurs.each do |entrepreneur| %>
	<li>
		<p><%= link_to "#{entrepreneur.first_name} #{entrepreneur.last_name}",
			entrepreneur_url(entrepreneur), method: :get %></p>
	</li>
	<% end %>
</ul>
<% end %>

<%= link_to_function "Back", "history.back()" %>