config/routes.rb
Investours::Application.routes.draw do
  resource :dashboard, only: [:show]
  resources :entrepreneurs do
      resources :projects, only: [:show, :edit, :update]
  end
  resources :loans
  resources :payments
  resources :sign_ups
  resources :tours
  resources :updates, only: [:create, :update, :destroy]
  devise_for :users
  get 'users/search', to: "users#search"
  get 'home', to: "visitors#welcome"
  
  authenticated :user do
    root :to => "dashboards#show"
  end
  root to: "visitors#welcome"
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title, :description, :entrepreneur_id, :fundraising_goal
  
  belongs_to :entrepreneur
  has_many :loans
  has_many :backers, through: :loans, source: :lender, uniq: true
  has_many :updates
    
  def amount_raised
    loans.map { |loan| loan.principal }.inject(:+) || 0
  end
    
  def progress_status
    amount_raised / (fundraising_goal || amount_raised) * 100
  end
  
  def fully_funded?
    amount_raised >= fundraising_goal
  end
  
  def amount_borrowed
    loans.map { |loan| loan.amount_owed }.inject(:+) || 0
  end
  
  def amount_repaid
    Loan.includes(:payments).where(project_id: id).map { |loan| loan.amount_paid }.inject(:+) || 0
  end
  
  def repayment_status
    amount_repaid / (amount_borrowed || amount_repaid) * 100
  end
    
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def show
    @project = Project.includes(:entrepreneur, :updates, :loans).order("updates.created_at").find(params[:id])
    @entrepreneur = @project.entrepreneur
    @updates = @project.updates

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
    
    authorize! :create, @project
  end

  def edit
    @entrepreneur = Entrepreneur.find(params[:entrepreneur_id])
    @project = Project.find(params[:id])
    
    authorize! :update, @project
  end

  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @project = Project.find(params[:id])
    @entrepreneur = Entrepreneur.find(params[:entrepreneur_id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to entrepreneur_url(@entrepreneur), notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to entrepreneur_projects_url(params[:entrepreneur]) }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<form for="project" action="<%= entrepreneur_project_url(@entrepreneur) %>" method="POST">
	<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
	<input name="_method" value="PUT" type="hidden">
	<label for="project_title">Title</label>
	<input id="project_title" name="project[title]" type="text" value="<%= @project.title %>">
	<br>
	<label for="project_description">Description</label>
	<textarea id="project_description" name="project[description]"><%= @project.description %></textarea>
	<br>
	<label for="project_fundraising_goal">Fundraising Goal</label>
	<input id="project_fundraising_goal" name="project[fundraising_goal]"
		type="number" value="<%= @project.fundraising_goal %>"
		>
	<br>
	<label for="project_fundraising_status">Fundraising Status</label>
	<input id="project_fundraising_status" name="project[fundraising_status]"
		type="number" value="<%= @project.fundraising_status %>"
		>
	<input type="Submit" value="Submit" >
</form>

app/views/projects/_mini_show.html.erb
<div><a href="<%= entrepreneur_project_url(project.entrepreneur, project) %>"><%= project.title %></a></div>

<%= render partial: "projects/status", locals: { project: project } %>

app/views/projects/_new_loan.html.erb
<div class="add_loan">
	<a href="#loan_form" class="add_loan_link">Record New Loan</a>
	<form action="<%= loans_url %>" method="POST">
		<div id="loan_form" class="modalDialog">
			<div>				
					<a href="#close" title="Close" class="close">X</a>
					
					<div class="errors">
					</div>
					
					<h2>Add a loan</h2>
					<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
					<label for="principal">Principal</label>
					<input id="principal" type="number" min="1" max="10000" name="loan[principal]">
					<br>
					<label for="lender">Lender</label>
					<input id="lender" type="text" class="search" autocomplete="off">
					<ul id="results">
					</ul>
					<input name="loan[entrepreneur_id]" value="<%= project.entrepreneur.id %>" type="hidden">
					<input name="loan[project_id]" value="<%= project.id %>" type="hidden">
					<input type="Submit" value="Save">
				</div>
		</div>
	</form>
</div>

<script type="text/javascript">
	
	drawLenders();
		
	$('input.search').searchbox({
		url: '/users/search',
		dom_id: '#results'
	});
	
	
	$("input[type='submit']").on('click', function (event) {
		recordLoan(event);
	});
	
</script>

app/views/projects/_new_payment.html.erb
<div class="add_payment">
	<a href="#payment_form" class="add_payment_link">Record New Payment</a>
	<form action="<%= payments_url %>" method="POST">
		<div id="payment_form" class="modalDialog">
			<div>				
					<a href="#close" title="Close" class="close">X</a>
					
					<div class="errors">
					</div>
					
					<h2>Add a Payment</h2>
					<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
					<label for="amount">Amount</label>
					<input id="amount" type="number" min="1" max="10000" name="payment[amount]">
					<br>
					<input name="payment[payer_id]" value="<%= project.entrepreneur.id %>" type="hidden">
					<p>Toward Loan:</p>
					<ul>
					<% project.loans.each do |loan| %>
						<% next if loan.paid_in_full? %>
						<li>
							<label for="loan-<%= loan.id %>">
								<%= "Loan #{loan.id} from #{loan.lender.full_name}." %>
							</label>
							<input id="loan-<%= loan.id %>" name="payment[loan_id]" type="radio" value="<%= loan.id %>">
							<div>
								<em><%= "$#{loan.amount_paid.to_f} repaid of $#{loan.amount_owed}." %>
								<%= "Made on #{loan.created_at.to_date} " %></em>
							</div>
						</li>
					<% end %>
					</ul>
					<input type="Submit" value="Save">
				</div>
		</div>
	</form>
</div>

<script type="text/javascript">
	
	$("input[type='submit']").on('click', function (event) {
		recordPayment(event);
	})
	
</script>

app/views/projects/_new_update.html.erb
<div class="add_update">
	<a href="#update_form" class="add_update_link">Add Update</a>
	<form action="<%= updates_url %>" method="POST">
		<div id="update_form" class="modalDialog">
			<div>				
					<a href="#close" title="Close" class="close">X</a>
					
					<div class="errors">
					</div>
					
					<h2>Update Project</h2>
					<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
					<label for="title">Title</label>
					<input id="title" type="text" name="update[title]">
					<br>
					<label for="body">Body</label>
					<textarea id="body" name="update[body]"></textarea>
					<input name="update[project_id]" value="<%= project.id %>" type="hidden">
					<input type="Submit" value="Save">
				</div>
		</div>
	</form>
</div>

app/views/projects/_progress_status.html.erb
<div>
	<p>$<%= project.amount_raised %> raised. $<%= project.fundraising_goal %> needed.</p>
	<div class='meter'>
		<span id="project-<%= project.id %>" style="width: <%= project.progress_status %>%"></span>
	</div>
</div>


<script type="text/javascript">
	$(function () {
		var $progressSpan = $(".meter > span#project-<%= project.id %>")
		animateProgressBar($progressSpan);
	})
</script>

app/views/projects/_project_status.html.erb
<% if project.fully_funded? %>
	<h2>Repayment Status</h2>
	<%= render partial: "projects/repayment_status", locals: { project: project } %>
<% else %>
	<h2>Progress Status</h2>
	<%= render partial: "projects/progress_status", locals: { project: project } %>
<% end %>

app/views/projects/_repayment_status.html.erb
<div>
	<p>$<%= project.amount_borrowed %> owed. $<%= project.amount_repaid %> repaid.</p>
	<div class='meter orange'>
		<span id="project-<%= project.id %>" style="width: <%= project.repayment_status %>%"></span>
	</div>
</div>


<script type="text/javascript">
$(function () {
	var $repaymentSpan = $(".meter > span#project-<%= project.id %>")
	animateProgressBar($repaymentSpan);
})
</script>

app/views/projects/_status.html.erb
<% if project.fully_funded? %>
	<div>Repaying Loans</div>
	<%= render partial: "projects/repayment_status", locals: { project: project } %>
<% else %>
	<div>Fundraising</div>
	<%= render partial: "projects/progress_status", locals: { project: project } %>
<% end %>

app/views/projects/_update.html.erb
<div>
	<h4><%= update.title %></h4>
	<p>By <%= update.author.full_name %> on <%= update.created_at.to_date %></p>
	<p><%= update.body %></p>
	<% if user_is_admin? %>
	<%= button_to "Delete Update", update_url(update), method: :delete, confirm: "Delete this update?" %>
	<% end %>
</div>

app/views/projects/_updates.html.erb
<div>
	<h2>Project Updates</h2>
	<% if updates.empty? %>
		<div>No updates yet.</div>
	<% else %>
		<ul>
			<% updates.each do |update| %>
				<li>
					<%= render partial: "update", locals: { update: update } %>
				</li>
			<% end %>
		</ul>
	<% end %>

	<% if user_is_admin? %>
		<%= render partial: "new_update", locals: { project: @project } %>
	<% end %>
</div>

app/views/projects/edit.html.erb
<h1>Update Project: <%= @project.title %></h1>

<%= render 'form', locals: { project: @project } %>

<%= link_to 'Show', entrepreneur_project_url(@entrepreneur, @project) %> |
<%= link_to 'Back', entrepreneur_project_url(@project.entrepreneur) %>

app/views/projects/index.html.erb
<h1>Listing Projects</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= link_to 'Show', entrepreneur_project_url(@entrepreneur, project) %></td>
    <td><%= link_to 'Edit', edit_entrepreneur_project_url(@entrepreneur, project) %></td>
    <td><%= link_to 'Destroy', entrepreneur_project_url(@entrepreneur, project),
				method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_entrepreneur_project_url(@entrepreneur) %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<div><a href="<%= entrepreneur_url(@entrepreneur) %>"><%= @entrepreneur.full_name %></a></div>
<div><%= @project.description %></div>


<%= render partial: "projects/status", locals: { project: @project } %>

<% if user_is_admin? %>
	<% if @project.fully_funded?%>
	<%= render partial: "projects/new_payment", locals: { project: @project } %>
	<% else %>
	<%= render partial: "projects/new_loan", locals: { project: @project } %>
	<% end %>
<% end %>

<%= render partial: "projects/updates", locals: { project: @project, updates: @updates } %>