config/routes.rb
Investours::Application.routes.draw do
  resource :dashboard, only: [:show]
  resources :entrepreneurs do
      resources :projects, only: [:show, :edit, :update]
  end
  resources :loans
  resources :payments
  resources :sign_ups
  resources :tours
  resources :updates, only: [:create, :update, :destroy]
  devise_for :users
  get 'users/search', to: "users#search"
  get 'home', to: "visitors#welcome"
  
  authenticated :user do
    root :to => "dashboards#show"
  end
  root to: "visitors#welcome"
end

app/models/loan.rb
class Loan < ActiveRecord::Base
  attr_accessible :entrepreneur_id, :lender_id, :project_id, :principal, :interest
  
  validates :entrepreneur_id, :lender_id, :principal, presence: true
  
  validate :project_cannot_be_fully_funded, :principal_cannot_exceed_project_need
  
  belongs_to :borrower, class_name: "Entrepreneur", foreign_key: :entrepreneur_id
  belongs_to :lender, class_name: "User", foreign_key: :lender_id, inverse_of: :loans
  belongs_to :project
  has_many :payments, dependent: :destroy
  
  def amount_owed
    principal + principal * interest
  end
  
  def amount_paid
    payments.map { |payment| payment.amount }.inject(:+) || 0
  end
  
  def oustanding_balance
    amount_owed - amount_paid
  end
  
  def repayment_status
    amount_paid / amount_owed * 100
  end
  
  def paid_in_full?
    amount_paid >= amount_owed
  end
  
  private
  
  def project_cannot_be_fully_funded
    return unless project
    errors.add(:project, "cannot be fully funded") if project.fully_funded?
  end
  
  def principal_cannot_exceed_project_need
    return unless principal
    if project.amount_raised + principal > project.fundraising_goal
      errors.add(:principal, "cannot exceed project funding requirement")
    end
  end
  
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @loans }
    end
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
    @loan = Loan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @loan }
    end
  end

  # GET /loans/new
  # GET /loans/new.json
  def new
    @loan = Loan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @loan }
    end
  end

  # GET /loans/1/edit
  def edit
    @loan = Loan.find(params[:id])
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(params[:loan])

    respond_to do |format|
      if @loan.save
        format.html { redirect_to :back, notice: 'Loan was successfully added.' }
        format.json { render json: @loan, status: :created, location: @loan }
      else
        format.html { render action: "new" }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
    authorize! :create, @loan
  end

  # PUT /loans/1
  # PUT /loans/1.json
  def update
    @loan = Loan.find(params[:id])

    respond_to do |format|
      if @loan.update_attributes(params[:loan])
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan = Loan.find(params[:id])
    @loan.destroy

    respond_to do |format|
      format.html { redirect_to loans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<%= form_for(@loan) do |f| %>
  <% if @loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% @loan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loans/edit.html.erb
<h1>Editing loan</h1>

<%= render 'form' %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<h1>Listing loans</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @loans.each do |loan| %>
  <tr>
    <td><%= link_to 'Show', loan %></td>
    <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
    <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Loan', new_loan_path %>

app/views/loans/new.html.erb
<h1>New loan</h1>

<%= render 'form' %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', loans_path %>